name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use node 22
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test
